import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
	...nextVitals,
	...nextTs,
	{
		rules: {
			// This codebase is non-strict TS (see CLAUDE.md) and uses `any` intentionally in places —
			// surface it, don't fail the lint run over existing usage.
			"@typescript-eslint/no-explicit-any": "warn",
			// Auto-fixable import grouping/sorting (`eslint --fix`). The `import` plugin is already
			// registered by eslint-config-next, no separate install needed.
			"import/order": [
				"warn",
				{
					groups: ["builtin", "external", "internal", "parent", "sibling", "index", "object", "type"],
					pathGroups: [
						{ pattern: "@/**", group: "internal" },
						{ pattern: "@api/**", group: "internal" },
					],
					pathGroupsExcludedImportTypes: ["builtin"],
					"newlines-between": "always",
					alphabetize: { order: "asc", caseInsensitive: true },
				},
			],
		},
	},
	globalIgnores([
		// Defaults from eslint-config-next
		".next/**",
		"out/**",
		"build/**",
		"next-env.d.ts",
		// Auto-generated by `supabase gen types typescript` — regenerated wholesale, not hand-edited
		"types/database/database.ts",
	]),
]);

export default eslintConfig;